### PR TITLE
rename from humantime_to_duration to parse_datetime

### PR DESCRIPTION
**Pull request by sylvestre**

### CODE REVIEW

**Comment by sylvestre** [comment]
@Benjscho WDYT?

**Review by tertsdiepraam — APPROVED** [review]
I agree this is better and we better change it before someone starts using it :)

**Comment by fritzmark** [comment]
I fear this destroyed the auto update. See my [comment](https://github.com/uutils/coreutils/issues/4967#issuecomment-1589679167).
Also installation fails now:

```shell
╰─> cargo uninstall coreutils
    Removing C:\Users\xxxxx\.cargo\bin\coreutils.exe
╰─> cargo install coreutils
    Updating crates.io index
  Installing coreutils v0.0.19
    Updating crates.io index
error: failed to compile `coreutils v0.0.19`, intermediate artifacts can be found at `C:\Users\xxxxx\AppData\Local\Temp\cargo-installlPgsr5`

Caused by:
  no matching package named `humantime_to_duration` found
  location searched: registry `crates-io`
  required by package `uu_date v0.0.19`
      ... which satisfies dependency `date = "^0.0.19"` of package `coreutils v0.0.19`
```

**Comment by sylvestre** [comment]
I don't think it is related. I think it is because I yanked the crate.
I revert it, could you please try again?
https://crates.io/crates/humantime_to_duration/0.3.1

**Comment by fritzmark** [comment]
Yeah that fixed it:

```shell
   Installed package `coreutils v0.0.19` (executable `coreutils.exe`)
```

**Pull request merged**
