### PR TITLE
Fix parsing when the local tz offset spans across midnight

### LINKED ISSUE #36: Cargo test fails at 0:20 JST
I ran `cargo test` on the current repo and got two errors:

```
failures:

---- test_from_str_at_date_day stdout ----
thread 'test_from_str_at_date_day' panicked at 'assertion failed: `(left == right)`
  left: `Duration { secs: 0, nanos: 0 }`,
 right: `Duration { secs: 86400, nanos: 0 }`', tests/simple.rs:133:5
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace

---- test_duration_parsing stdout ----
thread 'test_duration_parsing' panicked at 'assertion failed: `(left == right)`
  left: `Duration { secs: 31449600, nanos: 0 }`,
 right: `Duration { secs: 31536000, nanos: 0 }`', tests/simple.rs:16:5


failures:
    test_duration_parsing
    test_from_str_at_date_day

test result: FAILED. 4 passed; 2 failed; 0 ignored; 0 measured; 0 filtered out; finished in 0.01s

error: test failed, to rerun pass `--test simple`
```

I did not get the errors before, so it might have to do with the my timezone. It looks like there might be an error or a different usage between JST and UTC.

### PR DESCRIPTION
**Pull request by sruggier**
This should fix #36.

### CODE REVIEW

**Review by tertsdiepraam — CHANGES_REQUESTED** [review]
I understand what you're trying to do, but I don't think it's entirely correct in the long run. The problem is that we cannot return _just_ a `chono::Duration` because the length of the duration might depend on the date. For instance, if a duration of 1 month is given, that cannot be accurately represented in a `chrono::Duration`, because that only stores seconds and nanoseconds.

I think the calculation in `parse_relative_time_at_date` can probably be improved though.

**Comment by tertsdiepraam** [comment]
So, you're right, you've not regressed anything, but it would've if the rest up the code was correct (and obviously that's on us 😄). Basically, what the current main branch is currently doing, for example, is assuming that a month is 30 days. That's just wrong. It reality, the number of days that a month takes depends on the reference date.

However, there is an alternative solution that we could explore. Which is where we don't return just a `chrono::Duration`, but a custom duration, that includes the number of months as a separate field, for example. Like this library is doing: https://docs.rs/chronoutil/latest/src/chronoutil/relative_duration.rs.html#11-14. That would work too.

Sorry, this library is in a pretty weird state at the moment, because the original implementation did not foresee issues like this. I should sit down and really fix it up at some point.

**Comment by sruggier** [comment]
So, how do you want to proceed? I think it would be reasonable to merge this as-is, and open an issue to track the other problem. One can always revert the test removals later on if they'd be useful after making the later change.

If you'd prefer to fix both problems at the same.time, though, then it would be good to confirm that.

**Comment by tertsdiepraam** [comment]
No, sorry, I really can't merge this as is, because I've been really trying to push this library in the right direction (always having a reference datetime) and then this does not make sense. It's all related to the issues summarized here: https://github.com/uutils/parse_datetime/issues/56. Maybe, a solution would be to make this library not accept a `NaiveDate` as reference but a full `Datetime` and then add the parsed duration to that? I'll bump this library on my todo list and give it a good look today :)

**Comment by sruggier** [comment]
Yes, NaiveDates are part of the problem here.

**Comment by sylvestre** [comment]
should we close this PR ? thanks

**Comment by tertsdiepraam** [comment]
Thanks for your work on this! Feel free to reopen this or open a new PR if you think that we can give this a second shot.

**Pull request closed without merging**
